- hosts: all
  tasks:
    - name: Get hostname
      command: hostname
      register: hostname
      changed_when: false

    - when: inventory_hostname != hostname.stdout
      block:
        - name: Configure hostname
          hostname:
            name: "{{ inventory_hostname }}"
          become: true

        - debug:
            msg: "Hostname changed from {{ hostname.stdout }} to {{ inventory_hostname }}"
